### ISSUE TITLE
rss icon not visible

### ISSUE THREAD

**Issue by svenvanrijen** [AkshayAgarwal007/Jekyll-Mono#11]
Hi Akshay,

thanks for the great theme!
Unfortunatly, I'm not able to display the rss icon at the botom of the site. I've configured 'a' value for rss in the _config.yml but the icon won't display.

Can you please help me out? Thnx!

Kind regards,
Sven

**Comment by AkshayAgarwal007** [comment]
Thanks for pointing that out!
I have updated the same. You may sync your fork with the upstream source and let me know whether it's working or not.

**Comment by svenvanrijen** [comment]
Thanks Akshay! Icon works fine now!

Kind regards,
Sven
