### ISSUE TITLE
Contents of about.md not reflecting

### ISSUE THREAD

**Issue by codehakase** [AkshayAgarwal007/Jekyll-Mono#13]
I tried editing my forked version of the about.md file and even when i refresh the changes doesn't show up. 
@AkshayAgarwal007 
NB: i'm using github pages username.github.io/about 

and it's showing the demo lorem ipsum texts

**Comment by AkshayAgarwal007** [comment]
It's working fine.
![about](https://cloud.githubusercontent.com/assets/8170214/21811743/ce02c6be-d776-11e6-8768-b6119c988441.png)

**Comment by codehakase** [comment]
Thanks for the response, it was my browser's cache
