### ISSUE TITLE
Demo link is dead

### ISSUE THREAD

**Issue by omarwagih** [AkshayAgarwal007/Jekyll-Mono#19]
Demo link no longer works

**Comment by AkshayAgarwal007** [comment]
https://akshayagarwal007.github.io/Jekyll-Mono/
Works for me.. Screenshot?

**Comment by omarwagih** [comment]
From clicking demo link in readme.md
<img width="759" alt="screen shot 2017-07-21 at 19 59 49" src="https://user-images.githubusercontent.com/1717767/28476160-42e96a2c-6e4f-11e7-8f4d-801e903f328c.png">

**Comment by AkshayAgarwal007** [comment]
Should be fine now. I have removed the expired custom domain. Thanks for reporting this..!
