### ISSUE TITLE
What is a Profile cum blog?

### ISSUE THREAD

**Issue by sylhare** [AkshayAgarwal007/Jekyll-Mono#27]
Allo,

I was intrigued by the description of the theme.
 - What does cum mean? 

I have never heard about Profile cum blog 😅  and I am kinda scared of what internet would throw at me. Would it be:
- A type of blog? Like a cum blog.
- A type of Profile? Like so it is a blog about profile cum.
- An acronym? Like Profile *C*entered *U*ser *M*ainpage type of blog

Let me know 😉 Thanks!

The photo for reference
![Screenshot](https://user-images.githubusercontent.com/20642750/57324375-b051b300-70d5-11e9-919e-31117c045b98.png)

**Comment by glhr** [comment]
It's a latin word which means "with". For example, graduating "cum laude" means "with distinction". So in this case, "Profile cum blog" simply means something like "Profile & blog combined".

See:
https://grammarist.com/usage/cum/
https://en.wiktionary.org/wiki/cum#Latin
https://english.stackexchange.com/questions/26488/how-does-one-use-the-latin-word-cum-in-a-sentence

**Comment by sylhare** [comment]
Thank you! 😉 I feel more literate now.
